### PR TITLE
Gui binding:3.5

### PR DESCRIPTION
**Pull request by Konstantin8105**

### CODE REVIEW

**Comment by Konstantin8105** [comment]
#220

**Comment by Konstantin8105** [comment]
#197

**Comment by Konstantin8105** [comment]
#183

**Comment by gen2brain** [comment]
@Konstantin8105 thanks a lot. I would need some time to check all this. For now, I see that raygui.h is added in the core raylib directory, which is not correct as that is the separate, external module. Also, many files are touched, not sure for what reasons, there are places that include from your repo, etc. I don't like raygui3.5, what is with that, are we going to add a new dir for every version?

**Comment by Konstantin8105** [comment]
@gen2brain , just for information:
* The name of folder `raygui3.5` just for begin of that PR. At the end - we can replace original `raygui`. In my point of view, it is not clear your reason for creating Go implementation of GUI, but not CGO like in that PR. I also, do not like numbers in folder name.
* I do not add few widgets in my `raygui.go`, but indicate that - add warning. I will add later in that PR.
```
// Warning (*ast.FunctionDecl): {prefix: n:GuiCheckBox,t1:_Bool (Rectangle, const char *, 
_Bool),t2:}. C4GO/tests/raylib/raygui.h:535 :cannot transpileFunctionDecl. cannot 
bindingFunctionDecl func `GuiCheckBox`. cannot parse C type: `_Bool`
```
* In my point of view, we need a integration code coverage test for all packages. I will that about that later, maybe in next PR. What do you that about that?
* I need time for understood - how to move file `raygui.h` outside of folder `raylib`.
* In file `examples/gui/controls_test_suite/controls_test_suite.go` added `// TODO ...` for indicate some problem in implementation.

Please do not merge that PR before my and your requirements for PR.

This is a huge PR and if you want to continue that PR without me, then please clarify.

**Comment by gen2brain** [comment]
The reason why it was rewritten in Go would be clear when you move raygui.h out of raylib directory. The issue is described in https://github.com/gen2brain/raylib-go/issues/197 and in https://github.com/gen2brain/raylib-go/pull/183.

**Comment by Konstantin8105** [comment]
Hello,

* file `raygui.h` inside `raygui` folder.
* add more widgets
* replace all sources in `raygui`
* fix `gui` examples

`do doc` look badly, I hope fix in next PR.

In my point of view, all is ready.

**Comment by gen2brain** [comment]
Merged, thanks!

**Pull request merged**
