### PR TITLE
WIP: Update to raylib 5.5

### PR DESCRIPTION
**Pull request by JupiterRider**
#471 

@gen2brain as soon as the branch is ready to merge, I will tell you.

**ToDos:**
- [x] Update C-sources 
- [x] Update cgo bindings (raylib.h)
- [x] Update cgo bindings (rlgl.h)
- [x] Update purego bindings (raylib.h)
- [x] Update purego bindings (rlgl.h)

### CODE REVIEW

**Comment by JupiterRider** [comment]
@gen2brain The bindings are update and this PR is ready to merge.

**Comment by gen2brain** [comment]
Wow, this is nice, thanks. Can you please check https://github.com/gen2brain/raylib-go/blob/master/raylib/raudio.c#L1 and https://github.com/gen2brain/raylib-go/blob/master/raylib/platforms/rcore_android.c#L270. That is something that always must be done manually.

**Comment by gen2brain** [comment]
Also, there is a warning on macOS from `jar_xm`. I don't think anything has changed there, so our previous patched version is fine.

**Comment by JupiterRider** [comment]
> Wow, this is nice, thanks. Can you please check https://github.com/gen2brain/raylib-go/blob/master/raylib/raudio.c#L1 and https://github.com/gen2brain/raylib-go/blob/master/raylib/platforms/rcore_android.c#L270. That is something that always must be done manually.

The `!noaudio` build tags is added.

**Comment by JupiterRider** [comment]
> Wow, this is nice, thanks. Can you please check https://github.com/gen2brain/raylib-go/blob/master/raylib/raudio.c#L1 and https://github.com/gen2brain/raylib-go/blob/master/raylib/platforms/rcore_android.c#L270. That is something that always must be done manually.

@gen2brain The android platform is also fixed now.

**Comment by serrf0f** [comment]
@gen2brain can we merge this one?

@JupiterRider thanks a lot

**Comment by gen2brain** [comment]
@serrf0f I need to try it manually first. Did you test it, and does it work for you?

**Pull request merged**
