### PR TITLE
feat: update rtextures.go to have the func LoadTextureCubemap.

### PR DESCRIPTION
**Pull request by Gamerfiend**
Simple PR to update the bindings to allow use of a rl function.

### CODE REVIEW

**Comment by JupiterRider** [comment]
@Gamerfiend 
This is the purego signature:
`LoadTextureCubemap(image Image, layout int32) Texture2D`

Why don't you pass by value?

**Comment by Gamerfiend** [comment]
I’m not sure, I followed the same pattern established as the functions above it.

**Comment by Gamerfiend** [comment]
@JupiterRider If you look at LoadTextureFromImage for example, its the same.

**Comment by JupiterRider** [comment]
@Gamerfiend 
Could you update this function as well, so the signature matches?
https://github.com/gen2brain/raylib-go/blob/master/raylib/raylib_purego.go#L2640

Thanks

**Comment by Gamerfiend** [comment]
@JupiterRider I updated it :) I changed the behavior a little to match the way the Image pointer was handled above.

**Comment by JupiterRider** [comment]
Looks good!
@gen2brain I think this is ready for a merge

**Pull request merged**
