### PR TITLE
Adding gif and sprite animation examples.

### PR DESCRIPTION
**Pull request by Palessan**
-Added new UpdateTextureUnsafe method to support it.

### CODE REVIEW

**Comment by gen2brain** [comment]
There is no need for a new custom function, just use `unsafe.Slice((*color.RGBA)(unsafe.Pointer(uintptr(imScarfyAnim.Data)+uintptr(nextFrameDataOffset))), SIZE)`.

**Comment by gen2brain** [comment]
Btw. there is already https://github.com/gen2brain/raylib-go/tree/master/examples/textures/rectangle example, looks the same, maybe just it was renamed?

**Comment by Palessan** [comment]
> Btw. there is already https://github.com/gen2brain/raylib-go/tree/master/examples/textures/rectangle example, looks the same, maybe just it was renamed?

oh! then i'll remove mine and rename existing one as per original example name in raylib

**Comment by Palessan** [comment]
done

**Comment by gen2brain** [comment]
Is texScarfyAnimSize only width*height, looks like it is missing * 4?

**Comment by gen2brain** [comment]
Yeah, it actually should be like that, divided by 4, or not multiplied.

**Comment by gen2brain** [comment]
Merged, thanks!

**Comment by Palessan** [comment]
This was my first open source contribution!
Transferring my old pet game from XNA to raylib-go while learning Go : )

**Pull request merged**
