### PR TITLE
Updated Light.go - reflect.SliceHeader Deprecated

### PR DESCRIPTION
**Pull request by unklnik**
Created the Basic Lighting example and udpated Light.go also used in Mesh Instancing example as it used reflect.SliceHeader whic is deprecated. Have tested and it working should be fine

### CODE REVIEW

**Comment by unklnik** [comment]
Just wondering why this is taking so long to be added? I am sure you have other things to do however it is 100% working.

**Comment by unklnik** [comment]
Hi again, I would really like to add more examples though am still waiting for this one to be merged first when you have some time please. Thanks

**Comment by gen2brain** [comment]
There is a .exe file in this PR? @unklnik I do this in my free time when I find the time.

**Comment by unklnik** [comment]
Sorry, another thing, when I tried to make an example using Raygui the checks failed as it said it was unable to import Raygui. Do you know why maybe, the code works fine on my machine.

**Comment by unklnik** [comment]
This is the error it gave 

image


**_Error: shapes/draw_circle_sector/main.go:6:2: no required module provides package github.com/gen2brain/raylib-go/raygui; to add it:
	go get github.com/gen2brain/raylib-go/raygui_**

**Comment by gen2brain** [comment]
The gui examples are disabled, no idea, just don't add examples that use gui.

**Pull request merged**
