### PR TITLE
First approach for purego

### PR DESCRIPTION
**Pull request by JupiterRider**
My goal is not to touch any existing code and have a kind of drop in replacement.

(related to the discussion #306)

### CODE REVIEW

**Comment by gen2brain** [comment]
`platform_purego.go` is not a good filename, platform files now map perfectly to raylib core platforms, while purego would not essentially be a new platform. Something like `raylib_purego.go` would be better. Btw. I moved functions a little, so now raylib.go with all structs and definitions is cgo free. This also improves errors when there is no C compiler or CGO_ENABLED=0, before, the only cgo free file was raymath.go.

**Comment by JupiterRider** [comment]
@gen2brain Some functions still need to be implemented, but for now, its at least testable (no build-time errors).

Can I move the types `AudioCallback`, `Sound`, `Music`, `AudioStream` to raylib.go?

**Comment by gen2brain** [comment]
You cannot move AudioStream as there is https://github.com/gen2brain/raylib-go/blob/master/raylib/raudio.go#L98 and line 100. Those two first needs to be converted to Go, otherwise cgo will be used.

**Comment by gen2brain** [comment]
Ok, I added what is needed and I moved them to `raylib.go` in https://github.com/gen2brain/raylib-go/commit/3d34b7e25a5c73ce1788f329ead3b817246d2f60.

**Comment by JupiterRider** [comment]
@gen2brain It is done 🎉! All necessary functions are implemented.
Would be cool if you could merge this before Saturday - raylib's 10th birthday.

**Comment by JupiterRider** [comment]
@gen2brain
Linux and Darwin do not work with purego, because it is not possible to pass structs bigger than 64 bits. 
On Windows that's no problem, because I can pass them by reference (as Pointer). That's what the ABI wants: https://learn.microsoft.com/en-us/cpp/build/x64-calling-convention?view=msvc-170

The examples should work now (except the ones who use raygui or rlgl).

The version check is implemented now.

**Comment by gen2brain** [comment]
Ok, thanks. Can you just add the `!cgo && windows` build tags, and remove all commented functions, and I will merge it?
What do you think, if the struct is converted to []byte via binary/encoding or unsafe, will that work on Linux?

**Comment by JupiterRider** [comment]
@gen2brain 
`!cgo && windows` build tags are added, commented functions have been removed, io/file functions have been removed and the functions signature's should now match with the cgo version

**Comment by JupiterRider** [comment]
>What do you think, if the struct is converted to []byte via binary/encoding or unsafe, will that work on Linux?

This only works for structs <= 64 bits.

Here is the current status for that: https://github.com/ebitengine/purego/issues/88#issuecomment-1601100186

**Comment by gen2brain** [comment]
Merged :) Thanks a lot! I will just review README to change the order.

**Pull request merged**
