### PR TITLE
For the PS3, the gamepad_input window needs to be taller

### PR DESCRIPTION
**Pull request by justinclift**
#### Before
input_gamepad_bug_1

#### After
input_gamepad_bug_2

I only have a PS3 controller to test with, so couldn't test with anything else. :wink:

### CODE REVIEW

**Comment by raysan5** [comment]
that's weird, PS3 gamepad should appear drawn in the screen... is it an official controller?

Also, I personally prefer a two column solution instead of window scaling...

**Comment by justinclift** [comment]
> that's weird, PS3 gamepad should appear drawn in the screen... is it an official controller?

Yep, it's definitely an original Sony one.  It came with the PS3 years ago. :wink:

dmesg and lsusb output in case they're useful:

```dmesg
[10230.960056] usb 3-2: new full-speed USB device number 2 using uhci_hcd
[10231.130152] usb 3-2: New USB device found, idVendor=054c, idProduct=0268
[10231.130159] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[10231.130163] usb 3-2: Product: PLAYSTATION(R)3 Controller
[10231.130166] usb 3-2: Manufacturer: Sony
[10231.193055] sony 0003:054C:0268.0006: Fixing up Sony Sixaxis report descriptor
[10231.193445] input: Sony PLAYSTATION(R)3 Controller as /devices/pci0000:00/0000:00:1a.0/usb3/3-2/3-2:1.0/input/input8
[10231.194399] sony 0003:054C:0268.0006: input,hiddev0,hidraw5: USB HID v1.11 Joystick [Sony PLAYSTATION(R)3 Controller] on usb-0000:00:1a.0-2/input0
[11684.648869] perf: interrupt took too long (4906 > 4902), lowering kernel.perf_event_max_sample_rate to 40000
```

```bash
$ sudo lsusb -d 054c:0268 -v 

Bus 003 Device 002: ID 054c:0268 Sony Corp. Batoh Device / PlayStation 3 Controller
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x054c Sony Corp.
  idProduct          0x0268 Batoh Device / PlayStation 3 Controller
  bcdDevice            1.00
  iManufacturer           1 Sony
  iProduct                2 PLAYSTATION(R)3 Controller
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           41
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     148
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```

**Comment by justinclift** [comment]
I'm ok with updating this PR to use the original window size and 2 columns if you reckon that'd be better? :smile:

**Comment by justinclift** [comment]
Just did a bit of quick debugging, and found why the PS3 controller name isn't matching.
The string the current example is looking for is:

    PLAYSTATION(R)3 Controller

A call to `GetGamepadName()` though is returning:

    Sony PLAYSTATION(R)3 Controller

It's pretty simple to update the example so it checks for a few different strings.  My question is should it be checking for **only** `Sony PLAYSTATION(R)3 Controller`, or should it be checking both? :smile:

**Comment by justinclift** [comment]
Heh Heh Heh.  Interestingly, the button assignments that display with the PS3 Controller image are all messed up.

I can make a PR to fix that for my controller... I'm not sure if that would mess things up for other people though.  Any ideas?

**Comment by justinclift** [comment]
Changing the PS3 button definitions in raylib.go to this makes things match my controller:

```
	// PS3 USB Controller Buttons
	GamepadPs3ButtonTriangle = 12
	GamepadPs3ButtonCircle   = 13
	GamepadPs3ButtonCross    = 14
	GamepadPs3ButtonSquare   = 15
	GamepadPs3ButtonL1       = 10
	GamepadPs3ButtonR1       = 11
	GamepadPs3ButtonL2       = 8
	GamepadPs3ButtonR2       = 9
	GamepadPs3ButtonStart    = 3
	GamepadPs3ButtonSelect   = 0
	GamepadPs3ButtonUp       = 4
	GamepadPs3ButtonRight    = 5
	GamepadPs3ButtonDown     = 6
	GamepadPs3ButtonLeft     = 7
	GamepadPs3ButtonPs       = 16

	// PS3 USB Controller Axis
	GamepadPs3AxisLeftX  = 0
	GamepadPs3AxisLeftY  = 1
	GamepadPs3AxisRightX = 2
	GamepadPs3AxisRightY = 3
	// [1..-1] (pressure-level)
	GamepadPs3AxisL2 = 8
	// [1..-1] (pressure-level)
	GamepadPs3AxisR2 = 9
```

One point is a bit confusing though.  With my controller the L2 and R2 "triggers" don't seem to be pressure things.  They're on/off buttons only as far as I know.  In the onscreen display, no value changes anywhere on the left side list for any kind of partial squeeze of the triggers.

Instead, they only seem to show up as a full "on" when the button is fully pressed on, and the 'DETECTED BUTTON:' line then shows it's id.  eg for L2:

input_gamepad_bug_3

Thoughts? :smile:

**Comment by justinclift** [comment]
Hmm, also... no axis values displaying for the the XYZ orientation of the controller itself?  Is that expected? :smile:

**Comment by justinclift** [comment]
Tested things out on two different model PS3 controllers here now - a Sixaxis and a DualShock 3.  Both of them need the changed button mappings from above to work correctly.  L2/R2 seems to be only on/off for both as well.

**Comment by raysan5** [comment]
are you on Linux?

**Comment by justinclift** [comment]
Yep, using Linux. :smile:

Maybe the button mapping definition needs an #ifdef check or something to adjust things based on ths OS?

**Comment by justinclift** [comment]
Took some time earlier today to get MSYS2 (64-bit) installed on my old Win7 gaming PC, then setup a working Go environment to try this out with.

Interestingly, both of my PS3 controllers are detected by the existing code, without needing a changed identifier string.

ps3 sixaxis plugged in but no driver installed v1

* It seems like the `ps3NameID` string matching code in main.go should be updated to accept either.  That should help it be more cross platform. :smile:
  * Haven't tried on macOS yet.  I do have a macOS system here, but it doesn't have a Go dev environment on it.  So, not just yet... :wink:

* It's interesting that only 4 axis entries are detected/shown for the controller.

* With my controllers, none of them seemed to send button events.  So, even though the controllers were detected, no amount of moving joysticks nor pressing buttons "did anything".
  * At a guess, this is probably because I haven't yet installed drivers for them. :wink:

@raysan5 Do you have a url for the official Sony drivers?

I spent a significant amount of time trying to find official drivers from Sony, without success.

There are mentions and guides around for 3rd party drivers:
* SCPToolkit
* MotionInJoy ← seems like malware

But nothing official looking that I could find. :man_shrugging:

**Comment by raysan5** [comment]
@justinclift Official PS3 drivers came with Playstation Mobile SDK (PSM), unfortunately, it was duscontinued some years ago... so, probably, no official PS3 drivers available at the moment.

**Comment by justinclift** [comment]
No worries @raysan5.  Doesn't seem like a good use of time for me to keep trying this bit then. :wink:

**Pull request closed without merging**
