### PR TITLE
Implement SetLoadFileDataCallback and SetLoadFileTextCallback (for go:embed FS)

### PR DESCRIPTION
**Pull request by gabstv**
Hello,

I implemented the optional raylib funcs `SetLoadFileDataCallback` and `SetLoadFileTextCallback` to allow loading files from go embed filesystems.

Usage example:

```go
package main

import (
	"embed"
	"os"
	"strings"

	rl "github.com/gen2brain/raylib-go/raylib"
)

var (
	//go:embed assets/*
	assets embed.FS
)

func main() {
    // ... game startup code
    // load from embedded:
    // texture := rl.LoadTexture("res://assets/gopher_pixel.png")
    // load from the FS
    // texture := rl.LoadTexture("path/to/file/img.png")
}

func init() {
	rl.SetLoadFileDataCallback(func(name string) ([]byte, error) {
		if strings.HasPrefix(name, "res://") {
			return assets.ReadFile(name[6:])
		}
		return os.ReadFile(name)
	})
	rl.SetLoadFileTextCallback(func(name string) (string, error) {
		if strings.HasPrefix(name, "res://") {
			b, err := assets.ReadFile(name[6:])
			return string(b), err
		}
		fd, err := os.ReadFile(name)
		if err != nil {
			return "", err
		}
		return string(fd), nil
	})
}
```

### CODE REVIEW

**Comment by gen2brain** [comment]
Hello,

Thanks, but I don't think I like this. Not sure what this is trying to solve and it adds some custom functions for something that is already available. There are already many raylib functions that you can use if you want to embed files:
```
LoadImageFromMemory
LoadFontFromMemory
LoadWaveFromMemory
LoadMusicStreamFromMemory
LoadShaderFromMemory
```

So just embed whatever file you need and just load it, there is no need for some "special" support for embed. Or I am missing something here?

**Comment by gabstv** [comment]
The main motivation for me to fork and implement this, was that `LoadModel` doesn't have a `FromMemory` counterpart. Implementing the callbacks seemed more canonical than having a FromMemory of all these functions:
```c
#if defined(SUPPORT_FILEFORMAT_OBJ)
    if (IsFileExtension(fileName, ".obj")) model = LoadOBJ(fileName);
#endif
#if defined(SUPPORT_FILEFORMAT_IQM)
    if (IsFileExtension(fileName, ".iqm")) model = LoadIQM(fileName);
#endif
#if defined(SUPPORT_FILEFORMAT_GLTF)
    if (IsFileExtension(fileName, ".gltf") || IsFileExtension(fileName, ".glb")) model = LoadGLTF(fileName);
#endif
#if defined(SUPPORT_FILEFORMAT_VOX)
    if (IsFileExtension(fileName, ".vox")) model = LoadVOX(fileName);
#endif
#if defined(SUPPORT_FILEFORMAT_M3D)
    if (IsFileExtension(fileName, ".m3d")) model = LoadM3D(fileName);
#endif
```

**Comment by gen2brain** [comment]
I don't think FromMemory for models would look like that, same as we have LoadImage, not LoadJPEG, LoadPNG, etc. but this is then probably better be moved as a feature request to raylib.

**Comment by gen2brain** [comment]
I was wrong, see here https://github.com/raysan5/raylib/issues/1501, anyway, best to be implemented it directly in raylib.

**Comment by gabstv** [comment]
In that thread, raysan5 concluded that for models (that can often rely on loading multiple files):
> Agree that file IO callbacks is the best (and probably only) option.

I can see that you may not like the callback functions, but they are canon: 
image

By the replies on that thread. I don't see any alternative other than using load callbacks for models any time soon.

But yeah, I understand if you don't want to support this in your binding. I just thought of sharing here if anyone else might need this solution.

**Comment by gen2brain** [comment]
@gabstv Yes, I prefer to not include some custom solutions, who will maintain it afterward. The solution should be implemented in raylib, then we can add it in Go bindings.

**Pull request closed without merging**
