### PR TITLE
Cleanup utils - especially logging

### PR DESCRIPTION
**Pull request by JupiterRider**
I think using our own logging system is bad, because 
1. `SetTraceLogCallback(fn TraceLogCallbackFun)` is useless in the current state
2. raylib already handles platform-ospecific logging: [https://github.com/raysan5/raylib/blob/master/src/utils.c#L123](https://github.com/raysan5/raylib/blob/master/src/utils.c#L123)
3. bit shifting doesn't make sense in this case, because for example who wants so see Error but not Fatal? 
4. raylib-go is a binding and should be close to the original

I also touched `HomeDir()`. Maybe someone can check if I didn't accidentally break the android version, which should return the internalDataPath.

Would be nice to hear the opinion of @iszla and @gen2brain to my pull request :)

### CODE REVIEW

**Comment by gen2brain** [comment]
Hi, sorry, I didn't yet get to see all the changes, with files removed, then added, etc. it is kinda hard to see the main change here. As I glanced through it I didn't like that runtime.GOOS check, there are platform-specific files all around, why check OS in runtime?

**Comment by JupiterRider** [comment]
That was a mistake I've noticed after the commit. There is no runtime.GOOS anymore.
Please just take a look at the final result ("Files Changed" in the pull).

Basically I just made the `rl.TraceLog` and `rl.SetLogLevel` a cgo Binding and redirected `rl.HomeDir` to `os.UserHomeDir` (exept for android, which still gives you the internal storage path).

**Comment by JupiterRider** [comment]
@gen2brain What do you think? If you want me to change anything, please let me know.

**Comment by gen2brain** [comment]
Merged, thanks!

**Pull request merged**
