### PR TITLE
update raylib and deps

### PR DESCRIPTION
**Pull request by juan-medina**
Hi, this is a big PR for update the C version of raylib plus dependencies, I tested all the available examples and looks ok, but further testing is required before merging, just in case I miss something.

I've not added every single new function, they are more.

*Update the *BlendMode* values*
```go
// BlendMode type
type BlendMode int32

// Color blending modes (pre-defined)
const (
	BlendAlpha          BlendMode = iota // Blend textures considering alpha (default)
	BlendAdditive                        // Blend textures adding colors
	BlendMultiplied                      // Blend textures multiplying colors
	BlendAddColors                       // Blend textures adding colors (alternative)
	BlendSubtractColors                  // Blend textures subtracting colors (alternative)
	BlendCustom                          // Blend textures using custom src/dst factors (use SetBlendModeCustom())
)
```

*New desktop platform functions*
```go
// IsWindowMaximized - Check if window has been maximized (only PLATFORM_DESKTOP)
func IsWindowMaximized() 
// IsWindowFocused - Check if window has been focused
func IsWindowFocused()
// DecorateWindow - Decorate the window (only PLATFORM_DESKTOP)
func DecorateWindow() 
// UndecorateWindow - Undecorate the window (only PLATFORM_DESKTOP)
func UndecorateWindow() 
// MaximizeWindow - Maximize the window, if resizable (only PLATFORM_DESKTOP)
func MaximizeWindow() 
// RestoreWindow - Restore the window, if resizable (only PLATFORM_DESKTOP)
func RestoreWindow() 
// GetMonitorRefreshRate - Get primary monitor refresh rate
func GetMonitorRefreshRate(monitor int) int 
// GetWindowScaleDPI - Get window scale DPI factor
func GetWindowScaleDPI() Vector2 
// IsCursorOnScreen - Check if cursor is on the current screen.
func IsCursorOnScreen() bool
```
*Removed audio functions, (now the music loop by default)*
```go
// SetMusicLoopCount - Set music loop count (loop repeats)
func SetMusicLoopCount(music Music, count int32)
```

*Added Image functions*
```go
// UpdateTextureRec - Update GPU texture rectangle with new data
func UpdateTextureRec(texture Texture2D, rec Rectangle, pixels []Color)
```

*Changed Text function*
```go
func ImageDrawText(dst *Image, position Vector2, text string, fontSize int32, color Color)
```
is now

```go
func ImageDrawText(dst *Image, posX, posY int32, text string, fontSize int32, color Color) 
```

*Removed Image functions*
```go
// LoadImageEx - Load image data from Color array data (RGBA - 32bit)
func LoadImageEx(pixels []Color, width, height int32) *Image
// LoadImagePro - Load image from raw data with parameters
func LoadImagePro(data []byte, width, height int32, format PixelFormat) *Image
```
Because of this, the custom resources loader is not possible, see commit by @raysan5 https://github.com/raysan5/raylib/commit/cc816345bf24c8da911e080589b5653a52b8404e why was removed.

So I delete the example for custom resource loading.

However, I want to keep the capability of the go port to convert go img into raylib img, so I reimplement `NewImageFromImage`

```go
// NewImageFromImage - Returns new Image from Go image.Image
func NewImageFromImage(img image.Image) *Image {
	size := img.Bounds().Size()

	cx := (C.int)(size.X)
	cy := (C.int)(size.Y)
	ccolor := White.cptr()
	ret := C.GenImageColor(cx, cy, *ccolor)

	for y := 0; y < size.Y; y++ {
		for x := 0; x < size.X; x++ {
			color := img.At(x, y)
			r, g, b, a := color.RGBA()
			rcolor := NewColor(uint8(r), uint8(g), uint8(b), uint8(a))
			ccolor = rcolor.cptr()

			cx = (C.int)(x)
			cy = (C.int)(y)
			C.ImageDrawPixel(&ret, cx, cy, *ccolor)
		}
	}
	v := newImageFromPointer(unsafe.Pointer(&ret))
	return v
}
```
I test with the texture/to_image example and it works fine.

Finally, I got problems trying to compile the code with this struct

```go
// AudioStream type
// NOTE: Useful to create custom audio streams not bound to a specific file
type AudioStream struct {
	// Frequency (samples per second)
	SampleRate uint32
	// Bit depth (bits per sample): 8, 16, 32 (24 not supported)
	SampleSize uint32
	// Number of channels (1-mono, 2-stereo)
	Channels uint32
	// Buffer
	Buffer *_Ctype_struct_rAudioBuffer
}
```

Got errors with the `_Ctype_struct_rAudioBuffer` so I change it to get it compiling fine:

```go
// AudioStream type
// NOTE: Useful to create custom audio streams not bound to a specific file
type AudioStream struct {
	// Frequency (samples per second)
	SampleRate uint32
	// Bit depth (bits per sample): 8, 16, 32 (24 not supported)
	SampleSize uint32
	// Number of channels (1-mono, 2-stereo)
	Channels uint32
	// Buffer
	Buffer *C.rAudioBuffer
}
```

### CODE REVIEW

**Comment by juan-medina** [comment]
ups I miss an example `examples/textures/raw_data/main.go`

this part will not work since the removal of LoadImageEx

```go
	// Load pixels data into an image structure and create texture
	checkedIm := rl.LoadImageEx(pixels, int32(width), int32(height))
	checked := rl.LoadTextureFromImage(checkedIm)
	rl.UnloadImage(checkedIm) // Unload CPU (RAM) image data
```
I can delete the example, or just the logic for that, the LoadImageRaw works

**Comment by gen2brain** [comment]
Can you just add a build tag so noaudio tag can work https://github.com/gen2brain/raylib-go/blob/master/raylib/raudio.c#L1

Also, in core.c, android_main needs to be changed si it can work, see here https://github.com/gen2brain/raylib-go/blob/master/raylib/core.c#L555

Thanks!

**Comment by raysan5** [comment]
@gen2brain @juan-medina Please note that there is an open issue https://github.com/raysan5/raylib/issues/1367 that will probably remove some of the added Windows functions becasue the mechanism is being redesigned.

**Comment by juan-medina** [comment]
> 
> 
> @gen2brain @juan-medina Please note that there is an open issue [raysan5/raylib#1367](https://github.com/raysan5/raylib/issues/1367) that will probably remove some of the added Windows functions because the mechanism is being redesigned.

I know @raysan5 I'm the guy talking with you about that in the main repo :)

I'll update back the port when we resolve that question :)

**Comment by juan-medina** [comment]
> 
> 
> Can you just add a build tag so noaudio tag can work https://github.com/gen2brain/raylib-go/blob/master/raylib/raudio.c#L1
> 
> Also, in core.c, android_main needs to be changed si it can work, see here https://github.com/gen2brain/raylib-go/blob/master/raylib/core.c#L555
> 
> Thanks!

Done, I do not have right now androiod sdk/ndk so I can not test it, could you, please?

**Comment by gen2brain** [comment]
@juan-medina still not ok, misses declaration of `android_run` func. Never mind, I will have to take a look anyway later, I only managed to compile with `noaudio` tag, I had some problems with miniaudio.
I want to check a few examples and will merge later today, thanks!

**Comment by juan-medina** [comment]
> 
> 
> @juan-medina still not ok, misses declaration of `android_run` func. Never mind, I will have to take a look anyway later, I only managed to compile with `noaudio` tag, I had some problems with miniaudio.
> I want to check a few examples and will merge later today, thanks!

Oh sorry about that >.< I updated miniaudio since was update in the c sources and olso used diferently

**Pull request merged**
