### PR TITLE
bindings for attaching/detaching mixed audio processor

### PR DESCRIPTION
**Pull request by agrigoryan**
Bindings for `AttachAudioMixedProcessor` and `DetachAudioMixedProcessor` calls.

### CODE REVIEW

**Comment by gen2brain** [comment]
Thanks. Can you also add bindings for purego? You can look at how it is done for SetAudioStreamCallback, it is simpler than for CGO. Also, is reflection really needed here? I don't mind the reflect, was just wondering.

**Comment by gen2brain** [comment]
Ah, sorry, purego already have this. I am trying to keep them in sync.

**Comment by agrigoryan** [comment]
The reflection is used to compare the functions, I don't see other way around it.

**Comment by agrigoryan** [comment]
Yep, purego has those functions.
I tried to come up with something for {Attach/Detach}AudiaStreamProcessor for cgo, but those attach to AudioStream, I wasn't able find a simple way to get that mapped from C..

**Comment by gen2brain** [comment]
Merged, thanks.

**Pull request merged**
